// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.gov.sspba.domain;

import br.gov.sspba.domain.CategoriaCNH;
import java.io.Serializable;

privileged aspect CategoriaCNH_Roo_Serializable {
    
    declare parents: CategoriaCNH implements Serializable;
    
    private static final long CategoriaCNH.serialVersionUID = 1L;
    
}
