// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.gov.sspba.domain;

import br.gov.sspba.domain.Devices;
import java.io.Serializable;

privileged aspect Devices_Roo_Serializable {
    
    declare parents: Devices implements Serializable;
    
    private static final long Devices.serialVersionUID = 1L;
    
}
