// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.gov.sspba.domain;

import br.gov.sspba.domain.UserAccount;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserAccount_Roo_Configurable {
    
    declare @type: UserAccount: @Configurable;
    
}
